[package]
name = "nmcu"
version = "0.1.0"
authors = ["Daniel Dulaney <dulaney.daniel@gmail.com>"]

[dependencies]
mio-serial = "0.8"
mio = "0.6"
clap = "2.31"
error-chain = "0.11"
log = "0.4"
env_logger = "0.5"
